name: cd

on:
  push:
    branches: ['releases-*' ]

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    name: Build and deploying docs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "notesforamit@gmail.com"
          git config --global user.name "Amit Joshi"    

      - name: Set up Python runtime
          - uses: actions/setup-python@v2.2.1
          with:
            python-version: 3.6
      - name: Install pipenv
          run: >-
            python -m pip install --upgrade pipenv wheel
      - name: Setup env pipenv
          run: |
            pipenv install
      - name: Build dist
          run: |
            make build-dist
      - name: Publish distribution 📦 to Test PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
            
